version: 2
updates:
  - package-ecosystem: npm
    directory: /tests/esm
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /tests/cjs-require
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /tests/cjs-import
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /tests
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - '*'
