name: Setup PNPM cache
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7

    # See https://github.com/actions/cache/blob/main/examples.md#node---npm
    - name: Get pnpm store directory
      id: pnpm-cache-dir
      shell: bash
      run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
